server:
  port: 8081
api:
  security:
    user: "user"
    password: "password"
# If would like to use source of data from file
#  path-to-json-counts-file: "./out.json"
#  interval-to-upload-json-file: "30"
